-- ============================================================
-- 0012: Align t08_expenses.expense_type vocabulary
-- ============================================================
-- Previous constraint allowed: labour, marketing, overhead, program_coaches, other
-- New constraint (per the spec, 2026-04-23): labour, marketing, overhead, mastermind, other
--
-- Migration also:
--   1. Remaps any existing `program_coaches` rows → `labour` (coaches are team)
--   2. Adds `mastermind` as a valid bucket
--   3. Keeps `other` for unknown-counterparty rows that need manual review
--
-- Safe to re-run: drops the old constraint by name if present, then re-adds.
-- ============================================================

-- 1. Remap legacy values so the new constraint doesn't reject existing rows
update t08_expenses
   set expense_type = 'labour'
 where expense_type = 'program_coaches';

-- 2. Drop the old check constraint (name is auto-generated by PostgreSQL —
--    find and drop whatever check currently constrains expense_type)
do $$
declare
  c_name text;
begin
  select con.conname
    into c_name
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace ns on ns.oid = rel.relnamespace
   where ns.nspname = 'public'
     and rel.relname = 't08_expenses'
     and con.contype = 'c'
     and pg_get_constraintdef(con.oid) ilike '%expense_type%'
   limit 1;

  if c_name is not null then
    execute format('alter table t08_expenses drop constraint %I', c_name);
  end if;
end $$;

-- 3. Add the new constraint with the operator's 5-bucket vocabulary
alter table t08_expenses
  add constraint t08_expenses_expense_type_check
  check (expense_type in ('labour','marketing','overhead','mastermind','other'));
